# Generated by Django 5.2.4 on 2025-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current position', null=True)),
                ('responsibilities', models.TextField(help_text='Enter each responsibility on a new line. They will be formatted as bullet points.')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
