# Generated by Django 5.2.4 on 2025-09-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('specs', models.JSONField(default=list)),
                ('shipping', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('merchant_pubkey', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('merchant_pubkey', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('shipping_zones', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.AddField(
            model_name='product',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.stall'),
        ),
    ]
